[project]
name = "pdfpreview"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.2"
dependencies = [
    "icecream>=2.1.10",
    "loguru>=0.7.3",
    "pathvalidate>=3.3.1",
    "pyside6>=6.10.2",
]
